import {
	RISK_CONTROLLED_MOMENTUM_V2_EXCLUSION_SHA256,
	RISK_CONTROLLED_MOMENTUM_V2_MANIFEST_SHA256,
	RISK_CONTROLLED_MOMENTUM_V2_UNIVERSE_NAME,
} from "@/lib/analysis/risk-controlled-momentum-v2-universe";
import { RISK_CONTROLLED_MOMENTUM_V2_HISTORY_POLICY } from "@/lib/analysis/risk-controlled-momentum-v2-history";

export const RISK_CONTROLLED_MOMENTUM_V2_DEVELOPMENT_VERSION = "1.0.0";
export const RISK_CONTROLLED_MOMENTUM_V2_DEVELOPMENT_ID =
	"etf-risk-controlled-momentum-development-v2";

export const RISK_CONTROLLED_MOMENTUM_V2_PROTOCOL = {
	protocolVersion: RISK_CONTROLLED_MOMENTUM_V2_DEVELOPMENT_VERSION,
	developmentId: RISK_CONTROLLED_MOMENTUM_V2_DEVELOPMENT_ID,
	registeredAt: "2026-08-21",
	sources: {
		universeName: RISK_CONTROLLED_MOMENTUM_V2_UNIVERSE_NAME,
		universeManifestSha256: RISK_CONTROLLED_MOMENTUM_V2_MANIFEST_SHA256,
		exclusionInventorySha256: RISK_CONTROLLED_MOMENTUM_V2_EXCLUSION_SHA256,
		rejectedPredecessor: {
			path: "artifacts/analysis/etf-cross-sectional-momentum-development-v1.json",
			sha256:
				"1e476977c19913731446490d7c19b23df2a81c116732b657cbb40142ae15dde9",
			decision: "reject_cross_sectional_momentum_strategy",
		},
		history: {
			path: RISK_CONTROLLED_MOMENTUM_V2_HISTORY_POLICY.outputPath,
			sha256Status: "must_be_registered_after_fetch_before_outcomes",
			sha256: null,
		},
	},
	dataAccess: {
		formationHistoryStartsAt: RISK_CONTROLLED_MOMENTUM_V2_HISTORY_POLICY.requestedFrom,
		portfolioStartsAt: "2009-01-01T00:00:00.000Z",
		portfolioEndsBefore: "2016-01-01T00:00:00.000Z",
		firstFormationMonth: "2008-12",
		lastFormationMonth: "2015-11",
		expectedMonthlyHoldingPeriods: 84,
		protected2016PlusDataRead: false,
		existingValidationFeaturesRead: false,
		existingValidationLabelsRead: false,
		existingTestFeaturesRead: false,
		existingTestLabelsRead: false,
	},
	coverage: {
		manifestCandidates: 48,
		manifestCandidatesPerSleeve: 12,
		minimumBarsPerInstrument: 2_000,
		latestAllowedFirstBarAt: "2007-12-31T23:59:59.999Z",
		minimumEligibleInstruments: 40,
		minimumEligibleInstrumentsPerSleeve: 10,
		missingHistoryPolicy: "coverage_ineligible_without_replacement",
	},
	signal: {
		schedule: "last_completed_spy_session_of_each_calendar_month",
		formation: {
			formula: "adjusted_close_t_minus_21 / adjusted_close_t_minus_252 - 1",
			lookbackSessions: 252,
			skipRecentSessions: 21,
			minimumObservedSessions: 253,
		},
		absoluteEligibility: "formation_return_strictly_greater_than_zero",
		liquidity: {
			windowSessions: 20,
			minimumObservedSessions: 19,
			minimumMedianDollarVolume: 10_000_000,
			maximumTargetPositionFractionOfMedianDollarVolume: 0.01,
			dollarVolumeDefinition: "adjusted_close_times_reported_volume",
			missingDataPolicy: "candidate_ineligible",
		},
		selectionPerSleeve: 1,
		ranking: "formation_return_descending_within_sleeve",
		tieBreaker: "display_symbol_ascending",
	},
	portfolio: {
		initialEquity: 100_000,
		baseSleeveWeight: 0.2475,
		operationalCashReserveWeight: 0.01,
		maximumUnscaledGrossExposure: 0.99,
		maximumPositions: 4,
		longOnly: true,
		leverageAllowed: false,
		fractionalUnitsAllowed: true,
		cashReturnAnnualPercent: 0,
		execution: "next_common_session_adjusted_open_sell_before_buy",
		valuation: "daily_adjusted_close_shared_capital",
		finalLiquidation: "last_adjusted_close_before_development_boundary",
		missingExecutionOrValuationPolicy: "fail_experiment",
	},
	riskControl: {
		kind: "portfolio_volatility_target",
		returnDefinition: "adjusted_close_to_close_arithmetic_return",
		covarianceEstimator: "sample_covariance",
		windowCommonSessions: 20,
		minimumCommonReturns: 19,
		annualizationSessions: 252,
		targetAnnualizedVolatility: 0.1,
		formula:
			"min(1, target_volatility / sqrt(252 * unscaled_weights_transpose * covariance * unscaled_weights))",
		maximumMultiplier: 1,
		missingOrNonpositiveVolatilityMultiplier: 0,
		recalculation: "after_every_completed_common_session",
		execution: "next_common_session_adjusted_open",
		parameterGridAllowed: false,
		volatilityFloor: null,
		smoothing: null,
	},
	costs: {
		base: { transactionCostBpsPerSide: 2, slippageBpsPerFill: 3 },
		stress: { transactionCostBpsPerSide: 4, slippageBpsPerFill: 6 },
		turnover:
			"one_half_sum_absolute_changes_across_risky_and_cash_weights_annualized_from_daily_mean_times_252",
	},
	comparators: {
		unscaledMomentum: "same_fresh_source_and_v1_mechanics_without_risk_multiplier",
		staticSleeves: "24_75_percent_per_sleeve_equal_weight_members_with_1_percent_cash",
		spyBuyAndHold: "99_percent_adjusted_spy_with_1_percent_cash",
		costs: "same_base_entry_rebalance_and_exit_cost_accounting_where_applicable",
	},
	developmentGates: [
		{ metric: "monthly_holding_periods", operator: "=", threshold: 84 },
		{ metric: "coverage_eligible_instruments", operator: ">=", threshold: 40 },
		{ metric: "minimum_coverage_eligible_per_sleeve", operator: ">=", threshold: 10 },
		{ metric: "minimum_candidates_in_any_sleeve_decision", operator: ">=", threshold: 5 },
		{ metric: "months_with_any_investment", operator: ">=", threshold: 42 },
		{ metric: "base_net_annualized_return_percent", operator: ">=", threshold: 5 },
		{ metric: "stress_net_annualized_return_percent", operator: ">=", threshold: 3 },
		{ metric: "base_monthly_sharpe", operator: ">=", threshold: 0.5 },
		{ metric: "base_maximum_drawdown_percent", operator: "<=", threshold: 20 },
		{ metric: "stress_maximum_drawdown_percent", operator: "<=", threshold: 22 },
		{ metric: "drawdown_improvement_over_unscaled_percent_points", operator: ">=", threshold: 5 },
		{ metric: "monthly_sharpe_improvement_over_unscaled", operator: ">=", threshold: 0 },
		{ metric: "annualized_return_difference_vs_unscaled_percent", operator: ">=", threshold: -2 },
		{ metric: "annualized_return_improvement_over_static_percent", operator: ">=", threshold: 0 },
		{ metric: "positive_calendar_years", operator: ">=", threshold: 4 },
		{ metric: "minimum_calendar_year_return_percent", operator: ">=", threshold: -10 },
		{ metric: "minimum_selected_months_per_sleeve", operator: ">=", threshold: 24 },
		{ metric: "annualized_one_way_turnover_percent", operator: "<=", threshold: 1_200 },
		{ metric: "stress_annualized_return_difference_vs_base_percent", operator: ">=", threshold: -2 },
	] as const,
	report: {
		outputPath:
			"artifacts/analysis/etf-risk-controlled-momentum-v2-development-report.json",
		overwrite: false,
		instrumentLevelOutput: false,
		selectedSymbolsOutput: false,
		aggregates: [
			"overall_metrics",
			"calendar_years",
			"sleeve_selection_counts",
			"risk_multiplier_summary",
			"coverage_inventory",
			"comparators",
			"gates",
		] as const,
	},
	decisionPolicy: {
		requiresEveryGate: true,
		pass: "freeze_for_a_separately_preregistered_validation_on_new_data",
		fail: "reject_exact_v2_without_tuning_or_rerun_on_this_source",
		authorizesExistingValidationAccess: false,
		authorizesExistingTestAccess: false,
		authorizesProductSignals: false,
		authorizesLiveTrading: false,
	},
	prohibitions: [
		"Do not fetch history until this protocol and the guarded fetcher are reviewed together.",
		"Do not calculate outcomes until the fetched history checksum is registered without changing mechanics or gates.",
		"Do not test another volatility target, window, estimator, floor, smoothing rule, trend filter, stop, or target.",
		"Do not substitute symbols or weaken coverage after market data are retrieved.",
		"Do not emit selected symbols or instrument-level outcomes.",
		"Do not open or repurpose any existing 2016-plus, validation, or test data.",
	] as const,
} as const;
