// TradingView does not publish a bulk symbol-validation API. This exclusion set
// records Coinbase USD mappings that did not resolve in the live symbol catalog
// audit performed on 2026-08-14. Keep this list explicit so provider catalog
// syncs cannot re-enable instruments whose widgets display an invalid symbol.
const UNAVAILABLE_COINBASE_SPOT_SYMBOLS = new Set([
	"ACXUSD",
	"ANTUSD",
	"ATAUSD",
	"BITUSD",
	"BONDUSD",
	"BUSDUSD",
	"CLVUSD",
	"COVALUSD",
	"CRPTUSD",
	"DAIUSD",
	"DARUSD",
	"DDXUSD",
	"DESOUSD",
	"DREPUSD",
	"DYPUSD",
	"ENJUSD",
	"EOSUSD",
	"ERNUSD",
	"EURCUSD",
	"FISUSD",
	"FXUSD",
	"GALAUSD",
	"GALUSD",
	"GUSDUSD",
	"GYENUSD",
	"IDEXUSD",
	"JUPUSD",
	"KEEPUSD",
	"LITUSD",
	"LOKAUSD",
	"LRCUSD",
	"MATICUSD",
	"MCO2USD",
	"MEDIAUSD",
	"MIRUSD",
	"MKRUSD",
	"MOBILEUSD",
	"MONAUSD",
	"MOVEUSD",
	"MPLUSD",
	"MTLUSD",
	"MULTIUSD",
	"MUSDUSD",
	"MUSEUSD",
	"MXCUSD",
	"NESTUSD",
	"NUUSD",
	"OMGUSD",
	"OMNIUSD",
	"OOKIUSD",
	"ORNUSD",
	"PIRATEUSD",
	"PLAUSD",
	"POLYUSD",
	"PRQUSD",
	"PYUSDUSD",
	"QSPUSD",
	"QUICKUSD",
	"RAIUSD",
	"RBNUSD",
	"RENUSD",
	"REPUSD",
	"RGTUSD",
	"RLYUSD",
	"RNDRUSD",
	"RONINUSD",
	"SEAMUSD",
	"SNTUSD",
	"SYLOUSD",
	"SYNUSD",
	"TIMEUSD",
	"TONEUSD",
	"TRIBEUSD",
	"TRUUSD",
	"TVKUSD",
	"UNFIUSD",
	"UPIUSD",
	"USTUSD",
	"VGXUSD",
	"WAMPLUSD",
	"WBTCUSD",
	"WCFGUSD",
	"WLUNAUSD",
	"YFIIUSD",
]);

export function isTradingViewCoinbaseSpotSymbolAvailable(symbol: string) {
	const normalized = symbol.trim().toUpperCase();
	return (
		/^[A-Z0-9._-]{2,40}$/.test(normalized) &&
		!UNAVAILABLE_COINBASE_SPOT_SYMBOLS.has(normalized)
	);
}
